### ISSUE TITLE
Issues with the new version 1.21.111

### ISSUE THREAD

**Issue by MirMiksan** [oryxel1/Boar#34]
Hello! Your project is simply amazing, very few people are able to create such a great movement simulation. Thank you for that! However, I’ve encountered a problem: unfortunately, Boar refuses to work with the latest version of Geyser 2.8.4-b947. Some errors occur, along with an inventory desynchronization bug. The issue described in the posts below appears specifically on version 1.21.111, while on 1.21.101 everything works fine. Could you please let me know when you plan to update to a newer version of Geyser?

I also have an additional question would it be possible to implement an event system similar to Geyser, so that it would be possible to intercept moments when a player uses cheats and send notifications to the administration?

Here is one of such mistakes
```
[13:47:12 WARN] [io.netty.channel.DefaultChannelPipeline]: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.NoSuchMethodError: 'org.cloudburstmc.math.vector.Vector3i org.geysermc.geyser.util.BlockUtils.getBlockPosition(org.cloudburstmc.math.vector.Vector3i, int)'
        at ac.boar.anticheat.validator.ItemTransactionValidator.handle(ItemTransactionValidator.java:299) ~[?:?]
        at ac.boar.anticheat.packets.player.PlayerInventoryPackets.onPacketReceived(PlayerInventoryPackets.java:27) ~[?:?]
        at ac.boar.protocol.mitm.CloudburstReceiveListener.handlePacket(CloudburstReceiveListener.java:27) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.BedrockSession.onPacket(BedrockSession.java:119) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.BedrockPeer.onBedrockPacket(BedrockPeer.java:67) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.BedrockPeer.channelRead(BedrockPeer.java:256) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:356) ~[server.jar:3.4.0-SNAPSHOT (git-94368d50-b538)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:107) ~[server.jar:3.4.0-SNAPSHOT (git-
```
